export default {
  ABOUT_USER_REQUEST: 'ABOUT_USER_REQUEST',
  ABOUT_USER_SUCCESS: 'ABOUT_USER_SUCCESS',
  ABOUT_USER_FAILRE: 'ABOUT_USER_FAILURE',

  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

  SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
}