export default {
  UPDATE_NOTE_TREE: 'UPDATE_NOTE_TREE_OBJECT',

  GET_USER_ITEMS_REQUEST: 'GET_USER_ITEMS_REQUEST',
  GET_USER_ITEMS_SUCCESS: 'GET_USER_ITEMS_SUCCESS',
  GET_USER_ITEMS_FAILURE: 'GET_USER_ITEMS_FAILURE',
};
