export default {
  GET_TAG_NOTES_REQUEST: 'GET_TAG_NOTES_REQUEST',
  GET_TAG_NOTES_SUCCESS: 'GET_TAG_NOTES_SUCCESS',
  GET_TAG_NOTES_FAILURE: 'GET_TAG_NOTES_FAILURE',

  GET_USER_ITEMS_REQUEST: 'GET_USER_ITEMS_REQUEST',
  GET_USER_ITEMS_SUCCESS: 'GET_USER_ITEMS_SUCCESS',
  GET_USER_ITEMS_FAILURE: 'GET_USER_ITEMS_FAILURE',

  SELECT_ITEM: 'SELECT_NOTE_ITEM',

  SEARCH_BY_TITLE_REQUEST: 'SEARCH_BY_TITLE_REQUEST',
  SEARCH_BY_TITLE_SUCCESS: 'SEARCH_BY_TITLE_SUCCESS',
  SEARCH_BY_TITLE_FAILURE: 'SEARCH_BY_TITLE_FAILURE',

  GET_ITEM_REQUEST: 'GET_NOTE_BY_ID_REQUEST',
  GET_ITEM_SUCCESS: 'GET_NOTE_BY_ID_SUCCESS',
  GET_ITEM_FAILURE: 'GET_NOTE_BY_ID_FAILURE',

  UDPATE_NOTE_REQUEST: 'UPDATE_NOTE_REQUEST',
  UDPATE_NOTE_SUCCESS: 'UPDATE_NOTE_SUCCESS',
  UDPATE_NOTE_FAILURE: 'UPDATE_NOTE_FAILURE',

  UPDATE_NOTE_NODE_REQUEST: 'UPDATE_NOTE_NODE_REQUEST',
  UPDATE_NOTE_NODE_SUCCESS: 'UPDATE_NOTE_NODE_SUCCESS',
  UPDATE_NOTE_NODE_FAILURE: 'UPDATE_NOTE_NODE_FAILURE',

  ADD_NODE_CHILD: 'ADD_NODE_CHILD',
};
