export default {
  GET_TAGS_LIST_REQUEST: 'GET_TAGS_LIST_REQUEST',
  GET_TAGS_LIST_SUCCESS: 'GET_TAGS_LIST_SUCCESS',
  GET_TAGS_LIST_FAILURE: 'GET_TAGS_LIST_FAILURE',

  GET_TAG_NODES_REQUEST: 'GET_TAG_NODES_REQUEST',
  GET_TAG_NODES_SUCCESS: 'GET_TAG_NODES_SUCCESS',
  GET_TAG_NODES_FAILURE: 'GET_TAG_NODES_FAILURE',

  ADD_TAG_REQUEST: 'ADD_TAG_REQUEST',
  ADD_TAG_SUCCESS: 'ADD_TAG_SUCCESS',
  ADD_TAG_FAILURE: 'ADD_TAG_FAILURE',

  UPDATE_TAG_REQUEST: 'UPDATE_TAG_REQUEST',
  UPDATE_TAG_SUCCESS: 'UPDATE_TAG_SUCCESS',
  UPDATE_TAG_FAILURE: 'UPDATE_TAG_FAILURE',

  REMOVE_TAG_REQUEST: 'REMOVE_TAG_REQUEST',
  REMOVE_TAG_SUCCESS: 'REMOVE_TAG_SUCCESS',
  REMOVE_TAG_FAILURE: 'REMOVE_TAG_FAILURE',

  GET_ITEMS_BY_NOTE_REQUEST: 'GET_NOTE_TAGS_REQUEST',
  GET_ITEMS_BY_NOTE_SUCCESS: 'GET_NOTE_TAGS_SUCCESS',
  GET_ITEMS_BY_NOTE_FAILURE: 'GET_NOTE_TAGS_FAILURE',

  SELECT_TAG: 'SELECT_TAG',
  RESET_SELECT_TAG: 'RESET_SELECT_TAG',
};
